name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "zkfozfd3tsdhx3mjix74yvqll2wifscqm3ggz4fqzvokjy2soneq"
          github_token: "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"
          ado_organization: "chrisjhoar"
          ado_project: "Screen Draw Rooms"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100


